### ISSUE TITLE
Please provide an example with binding to a tcp port accessible externally.

### ISSUE THREAD

**Issue by topiaruss** [avinetworks/ansible-role-docker#1]
I'm having trouble with this:

```
roles:
  - role: avinetworks.docker
    become: yes
    docker_debug: True
    docker_exec_opts: -H tcp://0.0.0.0:2375
```

so I presume the exec opts are incorrect.
