### ISSUE TITLE
Can not use direct-lvm autoconfiguration mode

### ISSUE THREAD

**Issue by hopkins-tk** [avinetworks/ansible-role-docker#9]
Currently it is impossible to use Docker's direct-lvm autoconfiguration:
https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#allow-docker-to-configure-direct-lvm-mode

When I try to use:
```
    - role: avinetworks.docker
      docker_storage_driver: devicemapper
      docker_storage_opts:
        - "dm.directlvm_device=/dev/sdb"
        - "dm.basesize=25GB"
```
tasks for `devicemapper` will automatically try to create the volume manually and there is no possibility to disable it.
